//PRODUCTS

export const SET_PRODUCTS = "SET_PRODUCTS";
export const FETCH_PRODUCTS_FAILED = "FETCH_PRODUCTS_FAILED";
export const IS_ADDED_PRODUCT = "IS_ADDED_PRODUCT";

//ORDER

export const ADD_PRODUCT = "ADD_PRODUCT";
export const REMOVE_PRODUCT = "REMOVE_PRODUCT";
export const ADD_QUANTITY = "ADD_QUANTITY";
export const REMOVE_QUANTITY = "REMOVE_QUANTITY";
export const CLEAR_ORDER = "CLEAR_ORDER";

//AUTH

export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const CHANGE_MODAL_STATUS = "CHANGE_MODAL_STATUS";
